# Generated by Django 4.1.1 on 2022-09-23 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=254)),
                ('nombre', models.CharField(max_length=30)),
                ('DNI', models.IntegerField(help_text='DNI o Pasaporte')),
            ],
        ),
        migrations.CreateModel(
            name='rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rutina_hombro', models.CharField(max_length=30)),
                ('rutina_pecho', models.CharField(max_length=30)),
                ('rutina_triceps', models.CharField(max_length=30)),
                ('rutina_espalda', models.CharField(max_length=30)),
                ('rutina_biceps', models.CharField(max_length=30)),
                ('rutina_piernas', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='suplementos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Familia',
        ),
    ]
