# Generated by Django 4.1.1 on 2022-09-23 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_suplementos1_delete_suplementos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suplementos1',
            name='alanina',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='suplementos1',
            name='creatina',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='suplementos1',
            name='proteina',
            field=models.URLField(max_length=1000),
        ),
    ]
