# Generated by Django 4.1.1 on 2022-09-23 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0006_alter_index_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='DNI',
            field=models.CharField(max_length=10),
        ),
    ]
