# Generated by Django 4.1.1 on 2022-09-23 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0008_dni_delete_rutina'),
    ]

    operations = [
        migrations.CreateModel(
            name='dni1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DNI', models.CharField(max_length=10)),
                ('Apellido', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='DNI',
        ),
    ]
